name_one = input("Enter a name: ")
name_two = input("Enter another (different) name: ")
animal_one = input("Enter an animal: ")
animal_two = input("Enter another (different) animal: ")

print(name_one + " turned left on the sidewalk.")
print("The deer got hit by a car.")
print("A " + animal_one + " stepped over it.")
print(name_one + " killed the " + animal_one + " and the " + animal_one + " died.")
print(name_one + " is a serial killer, and he had planned the killing of the deer, 27 other children, and the " + animal_one + ".")
print("And then " + name_two + " killed " + name_one + ".")
print("A " + animal_two + " fell out of the sky and hit " + name_two + ", giving them emotional damage.")
print("The " + animal_two + " died of fall damage and created a very large red splat on the ground, infecting nearby pedestrians, starting the plague.")
print("THE END.")
